import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import init, { add } from "wasm-lib";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>
        <Link href="/calc">
          <a>Calculator (*test)</a>
        </Link>
      </p>
      <p>
        <Link href="/bfs">
          <a>Breadth-First Search (BFS)</a>
        </Link>
      </p>
    </div>
  );
};

export default Home;
